CREATE TABLE "FBSWTW_OWNER"."SWIMTX" 
(
  "SW_UMID" VARCHAR2(40 BYTE),
  "MESG_SESSION_HOLDER" VARCHAR2(30 BYTE),
  "MESG_CREATE_NO" VARCHAR2(10 BYTE),
  "MESG_TYPE" VARCHAR2(40 BYTE),
  "VALIDATION_FLAG" VARCHAR2(8 BYTE),
  "LAST_UPDATE_TIME" TIMESTAMP(6) DEFAULT 'swift.fin',
  "MX_MESG_TYPE" CLOB(40 BYTE)
) SEGMENT CREATION IMMEDIATE