-- =============================================
-- MHH Database Schema Initialization (MS SQL Server)
-- =============================================

USE [master];
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'MHH_DB')
BEGIN
    CREATE DATABASE [MHH_DB];
END
GO

USE [MHH_DB];
GO

-- 1. 使用者基礎帳號表
CREATE TABLE [USER] (
    [USER_ID] NVARCHAR(50) PRIMARY KEY,
    [USER_NAME] NVARCHAR(100) NOT NULL,
    [COUNTRY_CODE] NVARCHAR(10) NOT NULL,
    [STATUS] NVARCHAR(20) DEFAULT 'ACTIVE',
    [CREATED_AT] DATETIME DEFAULT GETDATE(),
    [UPDATED_AT] DATETIME DEFAULT GETDATE()
);

-- 2. 使用者自訂角色與權限映射表
CREATE TABLE [USER_ROLE] (
    [ROLE_ID] INT IDENTITY(1,1) PRIMARY KEY,
    [USER_ID] NVARCHAR(50) NOT NULL,
    [ROLE_NAME] NVARCHAR(50) NOT NULL, -- BRANCH_MAKER, BRANCH_CHECKER, PARAM_MAKER, PARAM_CHECKER
    [COUNTRY_CODE] NVARCHAR(10) NOT NULL,
    FOREIGN KEY ([USER_ID]) REFERENCES [USER]([USER_ID])
);

-- 3. 自定義使用者屬性配置表格
CREATE TABLE [USER_CUST] (
    [CUST_ID] INT IDENTITY(1,1) PRIMARY KEY,
    [USER_ID] NVARCHAR(50) NOT NULL,
    [ATTR_KEY] NVARCHAR(100),
    [ATTR_VALUE] NVARCHAR(MAX),
    [STATUS] NVARCHAR(20) DEFAULT 'PENDING', -- PENDING, APPROVED
    FOREIGN KEY ([USER_ID]) REFERENCES [USER]([USER_ID])
);

-- 4. HR 員工基本資料同步表
CREATE TABLE [HR_USER] (
    [EMP_ID] NVARCHAR(50) PRIMARY KEY,
    [EMP_NAME] NVARCHAR(100),
    [UNIT_CODE] NVARCHAR(20),
    [IS_ACTIVE] BIT DEFAULT 1,
    [LAST_SYNC] DATETIME DEFAULT GETDATE()
);

-- 5. HR 組織單位架構同步表
CREATE TABLE [HR_UNIT] (
    [UNIT_CODE] NVARCHAR(20) PRIMARY KEY,
    [UNIT_NAME] NVARCHAR(100),
    [PARENT_UNIT] NVARCHAR(20)
);

-- 6. SWIFT 電文歷史主表
CREATE TABLE [MSG_HISTORY] (
    [MSG_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [REFERENCE_NO] NVARCHAR(50),
    [SENDER_BIC] NVARCHAR(20),
    [RECEIVER_BIC] NVARCHAR(20),
    [MSG_TYPE] NVARCHAR(10), -- MT103, MT202, MX...
    [MSG_CONTENT] NVARCHAR(MAX),
    [FILE_PATH] NVARCHAR(500),
    [TRANS_DATE] DATE,
    [CREATED_AT] DATETIME DEFAULT GETDATE()
);

-- 7. 預約下載詳情與合併狀態表
CREATE TABLE [MSG_DOWNLOAD] (
    [DOWNLOAD_ID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [APPLICANT_ID] NVARCHAR(50) NOT NULL,
    [STATUS] NVARCHAR(20) DEFAULT 'PENDING', -- PENDING, APPROVED, MERGING, COMPLETED, EXPIRED
    [QUERY_CRITERIA] NVARCHAR(MAX),
    [FILE_COUNT] INT DEFAULT 0,
    [FILE_SIZE] BIGINT DEFAULT 0,
    [ZIP_PATH] NVARCHAR(500),
    [EXPIRY_DATE] DATETIME, -- 保留 6 個月
    [CREATED_AT] DATETIME DEFAULT GETDATE(),
    FOREIGN KEY ([APPLICANT_ID]) REFERENCES [USER]([USER_ID])
);

-- 8. 工作流審核任務表
CREATE TABLE [MSG_APPROVAL] (
    [APPROVAL_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [REF_ID] NVARCHAR(100), -- LINK TO DOWNLOAD_ID or CUST_ID
    [APPLICANT_ID] NVARCHAR(50),
    [APPROVER_ID] NVARCHAR(50),
    [TYPE] NVARCHAR(50), -- DOWNLOAD, USER_CUST, ROLE_CHANGE
    [STATUS] NVARCHAR(20), -- PENDING, APPROVED, REJECTED
    [REMARK] NVARCHAR(500),
    [CREATED_AT] DATETIME DEFAULT GETDATE(),
    [APPROVED_AT] DATETIME
);

-- 9. SWALLOW 原始資料同步至本系統之暫存表
CREATE TABLE [MSG_SWAL_SYNC] (
    [SYNC_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [RAW_DATA] NVARCHAR(MAX),
    [SYNC_STATUS] NVARCHAR(20) DEFAULT 'NEW',
    [CREATED_AT] DATETIME DEFAULT GETDATE()
);

-- 10. 系統運行日誌
CREATE TABLE [SYS_LOGS] (
    [LOG_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [LEVEL] NVARCHAR(10),
    [LOGGER] NVARCHAR(200),
    [MESSAGE] NVARCHAR(MAX),
    [EXCEPTION] NVARCHAR(MAX),
    [CREATED_AT] DATETIME DEFAULT GETDATE()
);

-- 11. 使用者行為稽核日誌
CREATE TABLE [USER_LOGS] (
    [AUDIT_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [USER_ID] NVARCHAR(50),
    [ACTION] NVARCHAR(100),
    [DETAILS] NVARCHAR(MAX),
    [IP_ADDRESS] NVARCHAR(50),
    [CREATED_AT] DATETIME DEFAULT GETDATE()
);

-- 12. 背景任務配置
CREATE TABLE [JOBS_CONF] (
    [JOB_NAME] NVARCHAR(100) PRIMARY KEY,
    [DESCRIPTION] NVARCHAR(200), -- 任務功能說明
    [CRON_EXPRESSION] NVARCHAR(50), -- 標準 Quartz/Cron 格式
    [IS_ENABLED] BIT DEFAULT 1, -- 開關狀態 (1: 啟用, 0: 停用)
    [LAST_RUN] DATETIME,
    [PARAMS] NVARCHAR(MAX) -- 擴充參數 (JSON 格式，由 IT 自行維護)
);

-- 13. 排程 Job 執行歷史
CREATE TABLE [JOBS_LOGS] (
    [RUN_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [JOB_NAME] NVARCHAR(100),
    [START_TIME] DATETIME,
    [END_TIME] DATETIME,
    [STATUS] NVARCHAR(20),
    [ERROR_MSG] NVARCHAR(MAX)
);
GO

-- Indices for Performance
CREATE INDEX [IDX_MSG_HISTORY_DATE] ON [MSG_HISTORY]([TRANS_DATE]);
CREATE INDEX [IDX_MSG_HISTORY_SENDER] ON [MSG_HISTORY]([SENDER_BIC]);
CREATE INDEX [IDX_USER_LOGS_USER] ON [USER_LOGS]([USER_ID]);
GO
