-- =============================================
-- MHH Database Schema Initialization (MS SQL Server)
-- =============================================

USE [master];
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'MHH_DB')
BEGIN
    CREATE DATABASE [MHH_DB];
END
GO

USE [MHH_DB];
GO

-- 1. 使用者基礎帳號表
CREATE TABLE [USER] (
    [USER_ID] NVARCHAR(50) PRIMARY KEY,
    [USER_NAME] NVARCHAR(100) NOT NULL,
    [COUNTRY_CODE] NVARCHAR(10) NOT NULL,
    [STATUS] NVARCHAR(20) DEFAULT 'ACTIVE',
    [CREATED_AT] DATETIME DEFAULT GETDATE(),
    [UPDATED_AT] DATETIME DEFAULT GETDATE()
);

-- 2. 使用者自訂角色與權限映射表
CREATE TABLE [USER_ROLE] (
    [ROLE_ID] INT IDENTITY(1,1) PRIMARY KEY,
    [USER_ID] NVARCHAR(50) NOT NULL,
    [ROLE_NAME] NVARCHAR(50) NOT NULL, -- BRANCH_MAKER, BRANCH_CHECKER, PARAM_MAKER, PARAM_CHECKER
    [COUNTRY_CODE] NVARCHAR(10) NOT NULL,
    FOREIGN KEY ([USER_ID]) REFERENCES [USER]([USER_ID])
);

-- 3. 自定義使用者屬性配置表格
CREATE TABLE [USER_CUST] (
    [CUST_ID] INT IDENTITY(1,1) PRIMARY KEY,
    [USER_ID] NVARCHAR(50) NOT NULL,
    [ATTR_KEY] NVARCHAR(100),
    [ATTR_VALUE] NVARCHAR(MAX),
    [STATUS] NVARCHAR(20) DEFAULT 'PENDING', -- PENDING, APPROVED
    FOREIGN KEY ([USER_ID]) REFERENCES [USER]([USER_ID])
);

-- 4. HR 員工基本資料同步表
CREATE TABLE [HR_USER] (
    [EMP_ID] NVARCHAR(50) PRIMARY KEY,
    [EMP_NAME] NVARCHAR(100),
    [UNIT_CODE] NVARCHAR(20),
    [IS_ACTIVE] BIT DEFAULT 1,
    [LAST_SYNC] DATETIME DEFAULT GETDATE()
);

-- 5. HR 組織單位架構同步表
CREATE TABLE [HR_UNIT] (
    [UNIT_CODE] NVARCHAR(20) PRIMARY KEY,
    [UNIT_NAME] NVARCHAR(100),
    [PARENT_UNIT] NVARCHAR(20)
);

-- 6a. 進電主表 (對齊 MsgIncoming.java)
CREATE TABLE [MSG_INCOMING] (
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [MESSAGE_ID] NVARCHAR(100) UNIQUE,
    [MESSAGE_TYPE] NVARCHAR(50),
    [SENDER] NVARCHAR(50),
    [RECEIVER] NVARCHAR(50),
    [AMOUNT] DECIMAL(18,5),
    [CURRENCY] NVARCHAR(3),
    [REFERENCE] NVARCHAR(100),
    [CONTENT] NVARCHAR(MAX),
    [PARAMETERS] NVARCHAR(MAX), -- JSON 格式彈性欄位
    [SYNC_TIME] DATETIME DEFAULT GETDATE(),
    [SOURCE] NVARCHAR(20) -- SWAL, PDF
);

-- 6b. 出電主表 (對齊 MsgOutgoing.java)
CREATE TABLE [MSG_OUTGOING] (
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [MESSAGE_ID] NVARCHAR(100) UNIQUE,
    [MESSAGE_TYPE] NVARCHAR(50),
    [SENDER] NVARCHAR(50),
    [RECEIVER] NVARCHAR(50),
    [AMOUNT] DECIMAL(18,5),
    [CURRENCY] NVARCHAR(3),
    [REFERENCE] NVARCHAR(100),
    [CONTENT] NVARCHAR(MAX),
    [PARAMETERS] NVARCHAR(MAX), -- JSON 格式彈性欄位
    [SYNC_TIME] DATETIME DEFAULT GETDATE(),
    [SOURCE] NVARCHAR(20) -- SWAL, PDF
);

-- 7. 預約下載詳情與合併狀態表
CREATE TABLE [MSG_DOWNLOAD] (
    [DOWNLOAD_ID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [APPLICANT_ID] NVARCHAR(50) NOT NULL,
    [STATUS] NVARCHAR(20) DEFAULT 'PENDING', 
    [QUERY_CRITERIA] NVARCHAR(MAX),
    [FILE_COUNT] INT DEFAULT 0,
    [FILE_SIZE] BIGINT DEFAULT 0,
    [ZIP_PATH] NVARCHAR(500),
    [EXPIRY_DATE] DATETIME,
    [CREATED_AT] DATETIME DEFAULT GETDATE(),
    FOREIGN KEY ([APPLICANT_ID]) REFERENCES [USER]([USER_ID])
);

-- 8. 工作流審核任務表
CREATE TABLE [MSG_APPROVAL] (
    [APPROVAL_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [REF_ID] NVARCHAR(100), 
    [APPLICANT_ID] NVARCHAR(50),
    [APPROVER_ID] NVARCHAR(50),
    [TYPE] NVARCHAR(50), 
    [STATUS] NVARCHAR(20), 
    [REMARK] NVARCHAR(500),
    [CREATED_AT] DATETIME DEFAULT GETDATE(),
    [APPROVED_AT] DATETIME
);

-- 9. SWALLOW 原始資料同步至本系統之暫存表 (Workflow A)
CREATE TABLE [MSG_SWAL_SYNC] (
    [SYNC_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [RAW_DATA] NVARCHAR(MAX),
    [SYNC_STATUS] NVARCHAR(20) DEFAULT 'NEW',
    [CREATED_AT] DATETIME DEFAULT GETDATE()
);

-- 10. 系統運行日誌 (對齊 SysLog.java)
CREATE TABLE [SYS_LOGS] (
    [LOG_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [LOG_LEVEL] NVARCHAR(10),
    [LOGGER_NAME] NVARCHAR(200),
    [MESSAGE] NVARCHAR(MAX),
    [STACK_TRACE] NVARCHAR(MAX),
    [CREATE_TIME] DATETIME DEFAULT GETDATE(),
    [NODE_IP] NVARCHAR(50)
);

-- 11. 使用者行為稽核日誌 (對齊 UserLog.java)
CREATE TABLE [USER_LOGS] (
    [LOG_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [USER_ID] NVARCHAR(50),
    [ACTION] NVARCHAR(100),
    [DESCRIPTION] NVARCHAR(MAX),
    [IP_ADDRESS] NVARCHAR(50),
    [LOG_TIME] DATETIME DEFAULT GETDATE(),
    [STATUS] NVARCHAR(20)
);

-- 12. 背景任務配置
CREATE TABLE [JOBS_CONF] (
    [JOB_NAME] NVARCHAR(100) PRIMARY KEY,
    [DESCRIPTION] NVARCHAR(200), 
    [CRON_SEC] NVARCHAR(10) DEFAULT '0', 
    [CRON_MIN] NVARCHAR(10) DEFAULT '0', 
    [CRON_HOUR] NVARCHAR(10) DEFAULT '0', 
    [CRON_DOM] NVARCHAR(10) DEFAULT '*', 
    [CRON_MONTH] NVARCHAR(10) DEFAULT '*', 
    [CRON_DOW] NVARCHAR(10) DEFAULT '?', 
    [IS_ENABLED] BIT DEFAULT 1, 
    [LAST_RUN] DATETIME,
    [PARAMS] NVARCHAR(MAX) 
);

-- 13. 排程 Job 執行歷史
CREATE TABLE [JOBS_LOGS] (
    [RUN_ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [JOB_NAME] NVARCHAR(100),
    [START_TIME] DATETIME,
    [END_TIME] DATETIME,
    [STATUS] NVARCHAR(20),
    [ERROR_MSG] NVARCHAR(MAX)
);
GO

-- Indices for Performance
CREATE INDEX [IDX_MSG_INCOMING_SYNC_TIME] ON [MSG_INCOMING]([SYNC_TIME]);
CREATE INDEX [IDX_MSG_INCOMING_SENDER]    ON [MSG_INCOMING]([SENDER]);
CREATE INDEX [IDX_MSG_OUTGOING_SYNC_TIME] ON [MSG_OUTGOING]([SYNC_TIME]);
CREATE INDEX [IDX_MSG_OUTGOING_SENDER]    ON [MSG_OUTGOING]([SENDER]);
CREATE INDEX [IDX_USER_LOGS_USER]         ON [USER_LOGS]([USER_ID]);
GO
